version: "3.8"
services:
    web:
        image: rahat6/nextjs-app:latest
        restart: always
        ports:
            - "3000:80"
        volumes:
            - web-data:/usr/share/nginx/html

volumes:
    web-data:
